phrase:

  access_token: "a3e4a3d014fa59e02fbb4684d22f9346cc380040eb33782181748f5c9791ebef"

  project_id: "6356b02341e40f0bdeac1975da1a70a9"

  file_format: "json"

  push:

    sources:

      - file: "./locales/*.json"

  pull:

    targets:

      - file: "./locales/<locale_name>.json"
