name: deployDev

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

env:
  DEPLOY_PATH: /www/roomcasino
  DEPLOY_DIR: dev
  BUILD_SCRIPT: npm run build:stage
  BUILD_SCRIPT_OUTPUT: .nuxt
  START_SCRIPT: PORT=3001 pm2 restart node_modules/nuxt-start/bin/nuxt-start.js --name roomcasino-sandbox -i max
  REPOSIRORY_NAME: wakeapp/roomcasino.git

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Записываем в переменные окружения имя текущей ветки
      # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
      - name: Get branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' | sed 's/\./_/g' | sed 's/[A-Z]/\L&/g')" >> $GITHUB_ENV
      # Доставляем приложение на сервер и запускаем его
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            rm -rf ${{ env.DEPLOY_DIR }}
            git clone 'https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ env.REPOSIRORY_NAME }}' ${{ env.DEPLOY_DIR }} --branch ${{ env.BRANCH_NAME }}
            cd ${{ env.DEPLOY_DIR }}
            npm i
            ${{ env.BUILD_SCRIPT }}
            ${{ env.START_SCRIPT }}
      - name: Print Info
        run: echo "http://${{ env.DEPLOY_DIR }}.sandbox.roomcasino.com/"
